CREATE EXTENSION citext;

CREATE TABLE users (
  id UUID PRIMARY KEY,
  name VARCHAR NOT NULL,
  email CITEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  avatar UUID,
  hash VARCHAR NOT NULL
);

