# This file serves as an example agent configuration to interact with the
# docker compose environment.
#
# You should pass the following command line flags when running the agent
# locally and using this file:
#
#   -enable-features=integrations-next -config.expand-env -config.enable-read-api
#
# -enable-features=integrations-next is required as the file is configured for
# the integrations revamp.
#
# -config.expand-env is required to expand environment variables. Environment
# variables are used when running the agent inside of docker-compose to connect
# to the other services. When running the agent externally, the expressions will
# default to the appropriate values of the exposed ports.
#
# -config.enable-read-api is optional, but allows you to invoke the /-/config
# endpoint to examine the generated config.

server:
  log_level: debug

metrics:
  global:
    scrape_interval: 2s
    remote_write:
    - url: http://mimir:9009/api/v1/push
  configs:
    - name: agent
      scrape_configs:
        - job_name: genbu
          static_configs:
            - targets: ['host.containers.internal:8080']

logs:
  configs:
  - name: default
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml

traces:
  configs:
  - name: default
    batch:
      timeout: 5s
      send_batch_size: 100
    remote_write:
      - endpoint: tempo:4317
        insecure: true
    receivers:
      jaeger:
        protocols:
          thrift_compact:
#
# Integrations
#
# Uncomment individual integrations below to enable them. Some integrations are
# enabled by default.
#

integrations:

  ## node_exporter
  # node_exporter: {}

  ## process
  # process:
  #   process_names:
  #     - name: "{{.Comm}}"
  #       cmdline:
  #       - '.+'

  ## mysql (requires docker-compose mysql profile)
  # mysql_configs:
  # - data_source_name: root@(${MYSQL_HOST:-localhost:3306})/

  ## postgres (requires docker-compose postgres profile)
  # postgres_configs:
  # - data_source_names:
  #   - postgresql://postgres:password@localhost:5432/postgres?sslmode=disable

  ## redis (requires docker-compose redis profile)
  # redis_configs:
  # - redis_addr: ${REDIS_HOST:-localhost:6379}

  ## dnsmasq (requires docker-compose dnsmasq profile)
  # dnsmasq_configs:
  # - dnsmasq_address: ${DNSMASQ_HOST:-localhost:30053}
  #   leases_path: /tmp/dnsmasq-leases/dnsmasq.leases

  ## memcached (requires docker-compose memcached profile)
  # memcached_configs:
  # - memcached_address: ${MEMCACHED_HOST:-localhost:11211}
  #   timeout: 10s

  ## statsd
  # statsd: {}

  ## consul (requires docker-compose consul profile)
  # consul_configs:
  # - server: http://${CONSUL_HOST:-localhost:8500}

  ## elasticsearch (requires docker-compose elasticsearch profile)
  # elasticsearch_configs:
  # - address: http://${ELASTICSEARCH_HOST:-localhost:9200}

  ## kafka (requires docker-compose kafka profile)
  # kafka_configs:
  # - kafka_uris: [${KAFKA_HOST:-localhost:9093}]

  ## github (requires docker-compose github profile)
  # github_configs:
  # - repositories:
  #   - grafana/agent

  ## mongodb (requires docker-compose mongodb profile)
  # mongodb_configs:
  # - mongodb_uri: mongodb://${MONGODB_HOST:-mongodb:27017}
  #   relabel_configs:
  #   - source_labels: [__address__]
  #     target_label: service_name
  #     replacement: 'mongodb'
  #   - source_labels: [__address__]
  #     target_label: mongodb_cluster
  #     replacement: 'mongodb-cluster'

  ## cadvisor
  # cadvisor:
  #   disabled_metrics:
  #   - disk
  #   enabled_metrics:
  #   - percpu

